stages:
  - build
  - deploy

build_docs:
  stage: build
  image: python:3.12
  script:
    - pip install sphinx sphinx-rtd-theme
    -  sphinx-apidoc -o docs/source/api src/chunkiter
    - make -C docs html
    - mv docs/build/html public
  artifacts:
    paths:
      - public
  only:
    - master

deploy_pages:
  stage: deploy
  script:
    - git config --global user.email "ci@example.com"
    - git config --global user.name "CI"
    - git remote set-url origin https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.com/leberwurscht/chunkiter.git
    - git checkout gh-pages
    - git rm -rf .
    - mv public/* .
    - git add .
    - git commit -m "Update docs" || echo "Nothing to commit"
    - git push -f origin gh-pages
  only:
    - master
