stages:
  - build
  - deploy

build_docs:
  stage: build
  image: python:3.12
  script:
    - pip install sphinx sphinx-rtd-theme
    - sphinx-apidoc -f -o docs/source/api src/chunkiter
    - make -C docs html
    - mv docs/build/html public
  artifacts:
    paths:
      - public
  only:
    - master

pages:
  stage: deploy
  dependencies:
    - build_docs
  script:
    - echo "Deploying GitLab Pages"
  artifacts:
    paths:
      - public
  only:
    - master
